'use client';
import { useEffect,useState } from 'react';
import { Dialog,DialogContent,DialogTitle } from '@/components/ui/dialog';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Toaster } from '@/components/ui/sonner';
import { toast as notify } from 'sonner';
import { Globe2,Bookmark,UserRound,Sparkles,Search,MapPin,GraduationCap,CalendarDays,X,ExternalLink,Check,ShieldCheck,SlidersHorizontal,ChevronDown,LoaderCircle,LogOut,Info } from 'lucide-react';
import Globe from './globe';
import { scholarships,destinations,levels,type Scholarship } from '../lib/catalog';
import countryNames from '../data/countries.json';

type Profile={name:string;nationality:string;level:string;field:string};
type Result=Scholarship&{reasons?:string[]};
type Interpreted={country:string;level:string;funding:string};
type View='explore'|'saved'|'profile';
const signIn='/signin-with-chatgpt?return_to=%2F';
const flag=(code:string)=>String.fromCodePoint(...[...code].map(c=>127397+c.charCodeAt(0)));
const initials=(name:string)=>name.split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase();

type APIResponse={error?:string;profile:Profile;saved:string[];results:Result[];interpreted:Interpreted};
function Choice({value,onChange,options,placeholder,label,id}:{value:string;onChange:(v:string)=>void;options:string[];placeholder:string;label:string;id?:string}){return <Select value={value||'__all'} onValueChange={v=>onChange(v==='__all'?'':v)}><SelectTrigger id={id} aria-label={label} className="choice-trigger"><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent className="choice-options" position="popper"><SelectItem value="__all">{placeholder}</SelectItem>{options.map(o=><SelectItem value={o} key={o}>{o}</SelectItem>)}</SelectContent></Select>}
async function api(path:string,options?:RequestInit){
 const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options?.headers}});
 const data=await r.json() as APIResponse;if(!r.ok)throw new Error(data.error||'Something went wrong. Please try again.');return data;
}
export default function Workspace({user}:{user:{displayName:string;email:string}|null}){
 const [view,setView]=useState<View>('explore'),[draft,setDraft]=useState(''),[query,setQuery]=useState('');
 const [country,setCountry]=useState(''),[level,setLevel]=useState(''),[funding,setFunding]=useState('');
 const [results,setResults]=useState<Result[]>(scholarships),[interpreted,setInterpreted]=useState<Interpreted>({country:'',level:'',funding:''});
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[accountError,setAccountError]=useState(''),[saved,setSaved]=useState<string[]>([]),[saving,setSaving]=useState<string[]>([]),[accountLoading,setAccountLoading]=useState(!!user);
 const [profile,setProfile]=useState<Profile>({name:'',nationality:'',level:'',field:''}),[profileBusy,setProfileBusy]=useState(false),[detail,setDetail]=useState<Result|null>(null),[authOpen,setAuthOpen]=useState(false),[aiOpen,setAiOpen]=useState(false),[limit,setLimit]=useState(5);
 const [refresh,setRefresh]=useState(0);
 useEffect(()=>{const read=()=>{const v=new URL(location.href).searchParams.get('view');setView(v==='saved'||v==='profile'?v:'explore');};read();window.addEventListener('popstate',read);return()=>window.removeEventListener('popstate',read)},[]);
 function navigate(v:View){setView(v);history.pushState({},'',v==='explore'?'/':'/?view='+v);window.scrollTo({top:0,behavior:'smooth'});}
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>Promise<unknown>};
  const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;const lifecycle=new AbortController();
  const register=(tool:Tool)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(console.error)}catch(e){console.error(e)}};
  register({name:'search_scholarships',description:'Search the curated scholarship catalog and display matching opportunities.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:500},country:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){const x=input as {query:unknown;country?:unknown};if(!x||typeof x.query!=='string'||x.query.length>500||x.country!==undefined&&typeof x.country!=='string')throw Error('Provide a search query and optional country.');const c=typeof x.country==='string'?x.country:'';const data=await api('/api/search',{method:'POST',body:JSON.stringify({query:x.query,country:c})});setDraft(x.query);setQuery(x.query);setCountry(c);setLevel('');setFunding('');setResults(data.results);setInterpreted(data.interpreted);navigate('explore');await new Promise(requestAnimationFrame);return {count:data.results.length,ids:data.results.map(s=>s.id)};}});
  register({name:'save_scholarship',description:'Save a scholarship to the authenticated user’s durable collection.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){const x=input as {id:unknown};if(!user)throw Error('Sign in to save scholarships.');if(!x||typeof x.id!=='string'||!scholarships.some(s=>s.id===x.id))throw Error('Unknown scholarship.');await api('/api/saved',{method:'POST',body:JSON.stringify({id:x.id})});setSaved(ids=>[x.id as string,...ids.filter(id=>id!==x.id)]);notify('Scholarship saved to your collection.');await new Promise(requestAnimationFrame);return {id:x.id,saved:true};}});
  return()=>lifecycle.abort();
 },[]);
 async function loadAccount(){if(!user)return;setAccountLoading(true);setAccountError('');try{const data=await api('/api/account');setProfile(data.profile);setSaved(data.saved);}catch(e){setAccountError((e as Error).message)}finally{setAccountLoading(false)}}
 useEffect(()=>{void loadAccount()},[]);
 useEffect(()=>{
  const controller=new AbortController();setBusy(true);setError('');setLimit(5);
  api('/api/search',{method:'POST',body:JSON.stringify({query,country,level,funding}),signal:controller.signal}).then(data=>{setResults(data.results);setInterpreted(data.interpreted);setBusy(false);}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setBusy(false)}});
  return()=>controller.abort();
 },[query,country,level,funding,refresh]);
 async function toggleSave(s:Scholarship){
  if(!user){setAuthOpen(true);return;}if(accountLoading||saving.includes(s.id))return;
  const isSaved=saved.includes(s.id);setSaving(ids=>[...ids,s.id]);
  try{await api('/api/saved',{method:isSaved?'DELETE':'POST',body:JSON.stringify({id:s.id})});setSaved(ids=>isSaved?ids.filter(id=>id!==s.id):[s.id,...ids]);notify(isSaved?'Removed from your saved scholarships.':'Scholarship saved to your collection.');setAccountError('');}
  catch(e){notify((e as Error).message)}finally{setSaving(ids=>ids.filter(id=>id!==s.id))}
 }
 function reset(){setDraft('');setQuery('');setCountry('');setLevel('');setFunding('');setError('');}
 function example(value:string){setDraft(value);setCountry('');setLevel('');setFunding('');setQuery(value);}
 const name=profile.name||user?.displayName||'Your profile';
 const visible=view==='saved'?scholarships.filter(s=>saved.includes(s.id)).sort((a,b)=>saved.indexOf(a.id)-saved.indexOf(b.id)):results;
 const selectedCountry=country||interpreted.country;
 const ready=user&&!accountLoading;
 function card(s:Result){const isSaved=saved.includes(s.id);return <article className="scholarship-card" key={s.id}>
  <div className="card-top"><div className={'provider-icon provider-'+s.countryCode}>{initials(s.provider)}</div><div className="provider-name">{s.provider}<span><MapPin size={12}/>{s.country}{s.countries?' & Canada':''}</span></div><button className={'save-button '+(isSaved?'is-saved':'')} aria-label={(isSaved?'Unsave ':'Save ')+s.title} aria-pressed={isSaved} disabled={saving.includes(s.id)||accountLoading} onClick={()=>void toggleSave(s)}>{saving.includes(s.id)?<LoaderCircle className="spin" size={19}/>:<Bookmark size={19} fill={isSaved?'currentColor':'none'}/>}</button></div>
  <button className="card-title" onClick={()=>setDetail(s)}>{s.title}</button>
  <p className="card-description">{s.description}</p>
  <div className="card-meta"><span className={'funding-tag '+(s.funding==='Full funding'?'full':'')}><span className="funding-mark"/> {s.funding}</span><span><GraduationCap size={14}/>{s.levels.join(' · ')}</span></div>
  <div className="card-bottom"><span><CalendarDays size={14}/>{s.deadlineDate&&new Date(s.deadlineDate)<new Date()?'Past deadline · ':''}{s.deadline}</span><button onClick={()=>setDetail(s)}>View details <ExternalLink size={13}/></button></div>
  {query&&s.reasons?.length?<div className="match-reason"><Sparkles size={12}/>{s.reasons.join(' · ')}</div>:null}
 </article>}
 return <div className="app-shell">
  <header className="topbar"><button className="brand" onClick={()=>navigate('explore')} aria-label="GlobeScholarship home"><span className="brand-icon"><Globe2 size={23}/></span><span>GlobeScholarship<span className="brand-ai">AI</span></span></button>
   <nav className="navigation" aria-label="Main navigation"><button className={view==='explore'?'active':''} onClick={()=>navigate('explore')}><Globe2 size={17}/>Explore</button><button className={view==='saved'?'active':''} onClick={()=>navigate('saved')}><Bookmark size={17}/>Saved{saved.length>0&&<span className="nav-count">{saved.length}</span>}</button><button className={view==='profile'?'active':''} onClick={()=>navigate('profile')}><UserRound size={17}/>Profile</button></nav>
   <div className="header-account"><span className="private-badge"><ShieldCheck size={14}/>Your workspace</span>{user?<button className="avatar" onClick={()=>navigate('profile')} aria-label="Open your profile">{initials(name)}</button>:<a className="sign-in" href={signIn} target="_top">Sign in</a>}</div>
  </header>
  {view==='explore'&&<main className="explore-layout">
   <aside className="world-panel"><div className="world-intro"><span className="eyebrow"><span className="tiny-star">✦</span> EXPLORE WITHOUT BORDERS</span><h1>Your next chapter.<br/><span>A world of possibility.</span></h1><p>Choose a country. Discover an opportunity.</p></div>
    <Globe selected={selectedCountry} onSelect={setCountry}/>
    <div className="globe-instruction"><span className="drag-mark">↔</span>Drag to rotate · Select a country to explore</div>
    <div className="destination-control"><label htmlFor="destination">YOUR STUDY DESTINATION</label><div className="destination-select"><MapPin size={18}/><Choice id="destination" label="Study destination" value={country} onChange={setCountry} options={countryNames} placeholder="Explore worldwide"/></div><div className="popular-countries">{['United States','Canada','United Kingdom','Germany'].map((c,i)=><button key={c} className={selectedCountry===c?'selected':''} onClick={()=>setCountry(country===c?'':c)}>{flag(['US','CA','GB','DE'][i])} {['USA','Canada','UK','Germany'][i]}</button>)}</div></div>
    <div className="world-footer"><span><strong>{scholarships.length}</strong> curated opportunities</span><span><strong>{destinations.length}</strong> study destinations</span></div>
   </aside>
   <section className="search-workspace"><div className="workspace-heading"><div><span className="section-eyebrow">YOUR SCHOLARSHIP JOURNEY</span><h2>Where will you go next?</h2><p>Find support for the future you have in mind.</p></div><button className="info-button" aria-label="How AI search works" onClick={()=>setAiOpen(true)}><Info size={18}/></button></div>
    <form className="search-box" onSubmit={e=>{e.preventDefault();setQuery(draft.trim());setRefresh(n=>n+1)}}><div className="search-label"><Sparkles size={16}/>AI scholarship search <span>Ask in your own words</span></div><div className="search-input-row"><input aria-label="Describe the scholarship you want" maxLength={500} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="e.g. Fully funded master’s in Germany"/><button className="primary" type="submit" disabled={busy}>{busy?<LoaderCircle size={17} className="spin"/>:<Search size={17}/>}Search</button></div></form>
    <div className="search-examples"><span>Try:</span>{['Undergraduate in Canada','Engineering in Korea','Fully funded master’s'].map(s=><button onClick={()=>example(s)} key={s}>{s}</button>)}</div>
    <div className="filters"><span className="filters-label"><SlidersHorizontal size={15}/>Refine</span><div className="filter-select"><Choice label="Study level" value={level} onChange={setLevel} options={levels} placeholder="All study levels"/></div><div className="filter-select"><Choice label="Funding type" value={funding} onChange={setFunding} options={['Full funding','Full tuition','Need-based','Partial funding','Varies']} placeholder="Any funding"/></div>{(query||country||level||funding)&&<button className="reset-filters" onClick={reset}>Reset</button>}</div>
    <div className="results-heading"><h3>{selectedCountry?selectedCountry:'Worldwide opportunities'}<span>{busy?'…':results.length}</span></h3><span className="curated-label"><Check size={13}/>Official sources</span></div>
    {(interpreted.level||interpreted.funding||interpreted.country)&&<div className="understood">Searching for: {[interpreted.country,interpreted.level,interpreted.funding].filter(Boolean).join(' · ')}</div>}
    <div aria-live="polite" aria-busy={busy} className={busy?'results-loading':''}>{error?<div className="empty-state"><Info size={27}/><h3>Search is unavailable</h3><p>{error}</p><button className="secondary" onClick={reset}>Try again</button></div>:results.length===0?<div className="empty-state"><Search size={30}/><h3>No matches this time</h3><p>{selectedCountry&&!destinations.includes(selectedCountry)?'This prototype’s curated catalog does not yet include opportunities in '+selectedCountry+'.':'Try a broader search or choose a different study level or destination.'}</p><button className="secondary" onClick={reset}>Explore all opportunities</button></div>:results.slice(0,limit).map(card)}</div>
    {!error&&results.length>limit&&<button className="load-more" onClick={()=>setLimit(limit+5)}>Show more opportunities <span>{results.length-limit} more</span></button>}
    <p className="catalog-note">A curated prototype, reviewed 3 October 2026. Confirm current deadlines and eligibility with each provider. <button onClick={()=>setAiOpen(true)}>About AI search</button></p>
   </section>
  </main>}
  {view==='saved'&&<main className="collection-page"><div className="page-heading"><span className="section-eyebrow">YOUR COLLECTION</span><h1>One step closer.</h1><p>Your saved scholarships, all in one place.</p></div>{!user?<div className="empty-state collection-empty"><Bookmark size={36}/><h2>Keep your possibilities close</h2><p>Sign in to save opportunities and find them here across your devices.</p><a className="primary" href={signIn} target="_top">Sign in with ChatGPT</a></div>:accountLoading?<div className="empty-state"><LoaderCircle className="spin"/><p>Loading your collection…</p></div>:accountError?<div className="empty-state"><h3>Your collection could not be loaded</h3><p>{accountError}</p><button className="secondary" onClick={()=>void loadAccount()}>Try again</button></div>:visible.length?<><div className="results-heading"><h3>Saved opportunities <span>{saved.length}</span></h3><button className="text-button" onClick={()=>navigate('explore')}>Explore more</button></div><div className="saved-grid">{visible.map(card)}</div></>:<div className="empty-state collection-empty"><Bookmark size={36}/><h2>Your next opportunity belongs here</h2><p>Tap the bookmark on a scholarship to add it to your collection.</p><button className="primary" onClick={()=>navigate('explore')}>Explore scholarships</button></div>}</main>}
  {view==='profile'&&<main className="profile-page"><div className="page-heading"><span className="section-eyebrow">YOUR SCHOLARSHIP JOURNEY</span><h1>A little about you.</h1><p>Keep your study interests in one simple profile.</p></div>{!user?<div className="empty-state collection-empty"><UserRound size={36}/><h2>Your journey starts with you</h2><p>Sign in to create your profile and keep your scholarships together.</p><a className="primary" href={signIn} target="_top">Sign in with ChatGPT</a></div>:<div className="profile-layout"><aside className="profile-summary"><div className="profile-avatar">{initials(name)}</div><h2>{name}</h2><p>{user.email}</p><span className="identity-badge"><ShieldCheck size={14}/>Signed in with ChatGPT</span><div className="profile-stat"><Bookmark size={17}/><strong>{saved.length}</strong>saved opportunities</div><a className="signout" href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={15}/>Sign out</a></aside><form className="profile-form" onSubmit={async e=>{e.preventDefault();setProfileBusy(true);try{const data=await api('/api/account',{method:'PUT',body:JSON.stringify(profile)});setProfile(data.profile);notify('Your profile is up to date.');setAccountError('');}catch(e){notify((e as Error).message)}finally{setProfileBusy(false)}}}><h2>Study profile</h2><p>Your study details are visible only to your signed-in account.</p>{accountError&&<div className="form-error">{accountError}<button type="button" onClick={()=>void loadAccount()}>Try again</button></div>}<fieldset disabled={accountLoading||profileBusy}><label>Display name<input required maxLength={80} value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} placeholder="Your name"/></label><label>Email<input value={user.email} readOnly/><span className="field-hint">Connected to your ChatGPT account</span></label><div className="form-columns"><label>Country of citizenship<input maxLength={80} value={profile.nationality} onChange={e=>setProfile({...profile,nationality:e.target.value})} placeholder="e.g. Ghana"/></label><label>Study level<Choice label="Profile study level" value={profile.level} onChange={v=>setProfile({...profile,level:v})} options={levels} placeholder="Choose your level"/></label></div><label>Field of interest<input maxLength={100} value={profile.field} onChange={e=>setProfile({...profile,field:e.target.value})} placeholder="e.g. Computer science"/></label><button className="primary" type="submit">{profileBusy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>}Save profile</button></fieldset></form></div>}</main>}
  <footer className="site-footer"><span><Globe2 size={14}/>GlobeScholarship AI</span><span>Possibility has no borders.</span><span><ShieldCheck size={13}/>Scholarship prototype</span></footer>
  <Toaster position="bottom-center"/>
  <Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="detail-dialog" showCloseButton={false} aria-describedby={undefined}>{detail&&<><div className="dialog-content"><button className="dialog-close" aria-label="Close scholarship details" onClick={()=>setDetail(null)}><X size={21}/></button><span className="detail-provider">{flag(detail.countryCode)} {detail.provider}</span><DialogTitle>{detail.title}</DialogTitle><div className="detail-tags"><span className="funding-tag full">{detail.funding}</span><span>{detail.levels.join(' · ')}</span><span>{detail.country}</span></div><p className="detail-description">{detail.description}</p><div className="detail-facts"><div><span>FUNDING</span><strong>{detail.amount}</strong></div><div><span>APPLICATION DEADLINE</span><strong>{detail.deadline}</strong></div></div><h3>What’s included</h3><ul>{detail.benefits.map(s=><li key={s}><Check size={16}/>{s}</li>)}</ul><h3>Who can apply</h3><ul className="eligibility-list">{detail.eligibility.map(s=><li key={s}>{s}</li>)}</ul><h3>Fields of study</h3><p>{detail.fields.join(' · ')}</p>{detail.note&&<div className="detail-note"><Info size={17}/><p>{detail.note}</p></div>}<p className="source-note">Reviewed {detail.checked}. Search relevance does not confirm eligibility. See the official provider for complete requirements.</p></div><div className="dialog-actions"><button className={'secondary '+(saved.includes(detail.id)?'saved-action':'')} disabled={saving.includes(detail.id)||accountLoading} onClick={()=>void toggleSave(detail)}><Bookmark size={17} fill={saved.includes(detail.id)?'currentColor':'none'}/>{saved.includes(detail.id)?'Saved to collection':'Save scholarship'}</button><a className="primary" href={detail.url} target="_blank" rel="noopener noreferrer">Official opportunity <ExternalLink size={16}/></a></div></>}</DialogContent></Dialog>
  <Dialog open={authOpen} onOpenChange={setAuthOpen}><DialogContent className="small-dialog" showCloseButton={false} aria-describedby={undefined}><button className="dialog-close" aria-label="Close sign-in prompt" onClick={()=>setAuthOpen(false)}><X size={20}/></button><div className="modal-icon"><Bookmark size={27}/></div><DialogTitle>Save your next possibility</DialogTitle><p>Sign in with ChatGPT to keep scholarships and your study profile together.</p><a className="primary" href={signIn} target="_top">Sign in with ChatGPT</a></DialogContent></Dialog>
  <Dialog open={aiOpen} onOpenChange={setAiOpen}><DialogContent className="small-dialog" showCloseButton={false} aria-describedby={undefined}><button className="dialog-close" aria-label="Close search explanation" onClick={()=>setAiOpen(false)}><X size={20}/></button><div className="modal-icon"><Sparkles size={28}/></div><DialogTitle>Search with a little more understanding.</DialogTitle><p>Describe a destination, study level, or field. A compact machine learning model ranks the curated catalog by semantic similarity and recognises study and funding preferences.</p><p>This prototype searches {scholarships.length} curated opportunities. It does not search the live web or determine whether you qualify. Every result links to the official provider.</p><button className="primary" onClick={()=>setAiOpen(false)}>Start exploring</button></DialogContent></Dialog>
 </div>
}
